### ISSUE TITLE
API

### ISSUE THREAD

**Issue by pepijnolivier** [2i18ns/i18ns.com#1]
Nice site!

Do you have an API or are you planning to add one ? It would be really cool if I could integrate this in a translation module 👌

**Comment by zyc945** [comment]
> Nice site!
> 
> Do you have an API or are you planning to add one ? It would be really cool if I could integrate this in a translation module 👌

Thanks for your support. the searching Api is on the road. maybe it's opened in the next week.

**Comment by 2i18ns** [comment]
> Nice site!
> 
> Do you have an API or are you planning to add one ? It would be really cool if I could integrate this in a translation module 👌

thank you for your support. Search Api is on the way. Maybe it will open as soon as next week.

**Comment by pepijnolivier** [comment]
Great! Thanks ! :)

**Comment by 2i18ns** [comment]
> Nice site!
> 
> Do you have an API or are you planning to add one ? It would be really cool if I could integrate this in a translation module 👌

The Api doc is here. https://i18ns.com/api.html
